# Rename me to secrets.yml
source:
  username: gmail_username
  password: gmail_password
  
twitter:
  consumer:
    key:    twitter_application_consumer_key
    secret: twitter_application_consumer_secret
  access:
    token: twitter_access_token
    secret: twitter_access_secret
