# Rename me to secrets.yml
source:
  username: gmail_username
  password: gmail_password
  
twitter:
  consumer:
    key:    twitter_application_consumer_key
    secret: twitter_application_consumer_secret
  account:
    username: twitter_account_username
    password: twitter_account_password
